export const pData = [
  {
    id: 1,
    name: "Anakin Skywalker",
    avatar: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/skywalker-ava.jpg",
    nickname: "@anakin-batya",
    date: "14 mar.",
    content: "WTF? Who is Ray? Why she is Skywalker? Luke...?",
    image: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/sw9_ReySabre-laser.jpg",
    message: { count: 482, isPressed: false },
    reTweet: { count: 146, isPressed: false },
    like: { count: 529, isPressed: false },
  },
  {
    name: "Emperor Palpatine",
    avatar: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/sheevPalpatine-ava.jpg",
    nickname: "@sheva-imperator",
    date: "17 apr.",
    content: "That woman could turn any Ewok into a Wookie.",
    image: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/sw9_PadmeAmidala-pictol.jpg",
    message: { count: 321, isPressed: false },
    reTweet: { count: 97, isPressed: false },
    like: { count: 784, isPressed: false },
  },
  {
    name: "Princess/General Leia Organa",
    avatar: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/leiaOrgana-ava.jpg",
    nickname: "@princess-Leia",
    date: "25 sep.",
    content: "What if you took Han Solo and gave him no depth?",
    image: "https://github.com/vitbon/hw20_react_redux/raw/master/public/img/sw9_PoeDameron-jet.jpg",
    message: { count: 296, isPressed: false },
    reTweet: { count: 138, isPressed: false },
    like: { count: 754, isPressed: false },
  }
];